### ISSUE TITLE
Progress tracker: Тараканов  Денис

### ISSUE THREAD

**Issue by dkurt** [dkurt/llama2.c.riscv#10]
- [x] Проект запущен на x86
- [x] Проект запущен на RISC-V без регрессии
- [x] Предложены тесты (PR)
- [x] Анализ производительности - метод (с примером команд или кодом) и результат. Доказать стабильность (написать результаты в комментариях к этой задаче)
- [x] Hotspot анализ + выбрана функция для оптимизации (написать результаты в комментариях к этой задаче)
- [x] Раунд оптимизации (PR)
- [ ] 1-2 слайда о своих результатах

**Comment by Chiks37** [comment]
Провёл hotspot анализ, выведя время выполнения самых долговыполняющихся функций и выяснил, что 75% от всего выполнения программы занимает функция matmul, выполняющая умножение матрицы на вектор.  Начал её векторизовать, используя технологию интринсиков для архитектуры riscv, однако ещё не закончил.

**Comment by Chiks37** [comment]
Доделал оптимизацию матричного умножения, но ещё не провёл тестирование, т.к. дома нет доступа к кластеру или эмулятору. Новый PR сделать по какой-то причине не удалось, однако в личном репозитории версия закоммичена.

**Comment by Chiks37** [comment]
Провёл оптимизацию функции matmul, используя технологию интринсиков для архитектуры riscv. Проводил тестирование на тесте 2 из файла test.c. Без оптимизации программа в среднем работала со скоростью 5.11 токенов в секунду, после оптимизации средняя скорость увеличилась до 8.87, т.е прирост скорости получился в ~1.74 раза.
