### ISSUE TITLE
Progress tracker: Пикин Илья

### ISSUE THREAD

**Issue by dkurt** [dkurt/llama2.c.riscv#8]
- [x] Проект запущен на x86
- [x] Проект запущен на RISC-V без регрессии
- [x] Предложены тесты (PR)
- [x] Анализ производительности - метод (с примером команд или кодом) и результат. Доказать стабильность (написать результаты в комментариях к этой задаче)
- [x] Hotspot анализ + выбрана функция для оптимизации (написать результаты в комментариях к этой задаче)
- [x] Раунд оптимизации (PR)
- [ ] 1-2 слайда о своих результатах

**Comment by IlyaPikin** [comment]
Я использовал linux-perf для анализа использования процессорного времени функциями, которые вызываются в testcc. 
Дополнительные ключи компиляции: `-O2 -g3 -fno-omit-frame-pointer`
Команды linux-perf:
`sudo perf record -e cycles,instructions -a -g -- ./testc`
`sudo perf report --stdio`
`sudo perf script | ./FlameGraph/stackcollapse-perf.pl --event-filter=cycles > out.perf-folded`
`./FlameGraph/flamegraph.pl out.perf-folded > Flame_Graph.svg`

В папке "PERF RESULTS" лежат все построенные флейм графы. Оказалось, что matmul() выполняет примерно 91% всей работы программы. В базовой версии программы при запуске на всех 5 тестах показатели скорости генерации токенов и общее время работы matmul() следующие:
  1. achieved tok/s: 31.619291
  2. achieved tok/s: 4.734497
  3. achieved tok/s: 4.642049
  4. achieved tok/s: 4.768786
  5. achieved tok/s: 4.605522
matmul() total time: 126.016564 seconds.

В параллельной версии с включенной OpenMP результаты такие:
  1. achieved tok/s: 51.589369
  2. achieved tok/s: 8.162612
  3. achieved tok/s: 7.948872
  4. achieved tok/s: 8.184524
  5. achieved tok/s: 7.936824
matmul() total time: 72.541316 seconds.

Векторизованная версия программы:
  1. achieved tok/s: 48.175182
  2. achieved tok/s: 8.036558
  3. achieved tok/s: 7.691118
  4. achieved tok/s: 7.956281
  5. achieved tok/s: 7.668889
matmul() total time: 72.806875 seconds.

Таким образом, ускорение matmul() в параллельной версии (4 потока) примерно в 1,7 раза.
Векторизация уменьшила суммарное время работы matmul() так же примерно в 1,7 раза.

VEC+OMP 4 threads

1. achieved tok/s: 54.425509
2. achieved tok/s: 8.410290
3. achieved tok/s: 7.958408
4. achieved tok/s: 8.203513
5. achieved tok/s: 8.071385

matmul() total time: 71.398188

VEC+OMP 2 threads

1. achieved tok/s: 56.701031
2. achieved tok/s: 8.759876
3. achieved tok/s: 8.381771
4. achieved tok/s: 8.677360
5. achieved tok/s: 8.334031

matmul() total time: 66.965953

Векторизация и OpenMP вместе дали ускорение в 1,88 раза.
