### ISSUE TITLE
Progress tracker: Гордеева Таисия

### ISSUE THREAD

**Issue by dkurt** [dkurt/llama2.c.riscv#9]
- [x] Проект запущен на x86
- [x] Проект запущен на RISC-V без регрессии
- [x] Предложены тесты (PR)
- [x] Анализ производительности - метод (с примером команд или кодом) и результат. Доказать стабильность (написать результаты в комментариях к этой задаче)
- [x] Hotspot анализ + выбрана функция для оптимизации (написать результаты в комментариях к этой задаче)
- [x] Раунд оптимизации (PR)
- [ ] 1-2 слайда о своих результатах

**Comment by TayaGordeeva** [comment]
Замеры выполнения функций:
tok/s:  5.096942
forward avg, ms: 195.000000
matmul avg, ms: 1.716430
generate ms: 20121.000000

Дополнительные значения:
encode, ms: 31.000000
main loop ms: 20274.000000
memory and file handles cleanup, ms: 80.000000
total test-time ms: 20422.000000

Выбранная функция для оптимизации: matmul

**Comment by TayaGordeeva** [comment]
Сделана оптимизация функции matmul. Функция стала работать быстрее в ~1.75 раз
Обновленные результаты:
tok/s:  8.828876
forward avg, ms: 112.000000
matmul avg, ms: 0.977633
generate, ms: 11553.000000
total test-time, ms: 11915.000000

**Comment by TayaGordeeva** [comment]
Также сделана оптимизация первого цикла в функции forward в части multihead. Данная оптимизация уменьшает время работы этой части (до оптимизации 444.000000ms; после оптимизации 359.000000ms), однако сама функция forward и программа в целом не намного быстрее работают (forward, ms: 111.000000, generate, ms: 11472.000000 и total time-test, ms: 11833.000000)
